matrix:
  include:
    - language: c
      sudo: required
      services:
        - docker
      script:
        - docker build -t swiftcommandline .

    - language: swift
      osx_image: xcode9.3
      script:
        - swift test
        - swift build
